app:
  build: .
  working_dir: /app
  volumes:
    - .:/app
  ports:
    - "80:8000"
  links:
    - queue:queue
  environment:
    - CELERY_BROKER_URL=redis://queue:6379/0
  command: /app/start_app.sh

worker:
  build: .
  working_dir: /app/hermes
  links:
    - queue:queue
    - app:app
  volumes_from:
    - app
  environment:
    - CELERY_BROKER_URL=redis://queue:6379/0
    - C_FORCE_ROOT=true
  command: /wait-for-it.sh app:8000 --timeout=300 --strict -- celery -A app.celery_app worker --loglevel=info

queue:
  image: redis
